language: python
sudo: required
apt:
  packages:
  - dos2unix
python:
- 2.7
- 3.4
- 3.5
- 3.6
install:
- pip install -r dev-requirements.txt
- pip install tox-travis
- PACKAGE_VERSION=`python setup.py --version`
- TAG_NAME=v$PACKAGE_VERSION
- python -m ldraw.download
- python -m ldraw.library_gen
before_install:
- sudo apt-get -qq update
- export TRAVIS_COMMIT_MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
- echo "$TRAVIS_COMMIT_MESSAGE"
script:
- tox
deploy:
  provider: pypi
  user: rienafairefr
  skip_cleanup: true
  password:
    secure: CSrPC1+LG99VJopqbg/NCsZFKjDv/ZuPUHuxUhqlIwrH7QQoWhC+/IRrSKqQJEwRLxCUKXNVq0rQ49xbsVpzHX9hxrrBNQPbdXUts7NNxL9yzMBKE+QwUoN0LDhRMtYTl2NBFM510KVtzMD10SdyD+JnZKocGt0qIR66Bvc/RxX1L0wcYI86qocUIx+6abTmwn+hiJvRDaSIvorZ41azOV4pMBoI6B8XbRg25ZdDOIF+Z9vr1ntsM/pxdlduk0NzAF6peOhmCjFXwCNy2Fm/QDJi7387BBr9SDHxXI43+aH8EMQLWC98ss9QcJOwqgxqwatyKUMMjY9LM5nnNCb41r5Zvuu1gMpkJ4V8uPQM5zOIAk76h51k2oDBDqGqh9ZuqcWCV7wtCX0wbtcCOjgs4Te36wAswUwdUfvalXz9UIlHYydXd7T7cckhQ25Nygi7QoYPIcXYa/PXoQJDoneOCUCwZnmGR2ACbntxoutj6oQ17ts6JtF2bLit2g81L13nHr4O+m2CF3KZNhWYs1i7CNedGFyZk4nvnxfKJiLUAJ+JPPDYoPkTq/Mape/m7nAPd9oabMW0N1tj1kyIYy7QsmBGUvvB12uAoEv4maND4nCTgK9O50cxMtuUMnCvLXTLDMU9hd0rDEtE5pB2DgfUxZS9PLi4A6xAE+yYOAz7YJ4=
  on:
    tags: true
    distributions: sdist bdist_wheel
    condition: $TRAVIS_PYTHON_VERSION = "2.7"
